# .github/release.yml
changelog:
  exclude:
    labels:
      - chore
      - dependencies
  categories:
    - title: 🚀 Features
      labels: [enhancement, feature]
    - title: 🐛 Bug Fixes
      labels: [bug, fix]
    - title: 📚 Documentation
      labels: [documentation, docs]
    - title: 🧹 Other Changes
      labels: ["*"]